### ISSUE TITLE
suggestion: use luks

### ISSUE THREAD

**Issue by sneak** [PhracturedBlue/syncthing-docker-encrypt#1]
This leaves the encryption keys in a lot of places... the `.bash_history`, the running docker process, the docker config files on disk (unencrypted)... as you note, it's not a very secure system.

A better idea is to mount a LUKS-encrypted file/partition on the host, using `cryptsetup`, and provide the key via SSH.  The key will be stored in kernel memory only, and won't appear anywhere on disk, or anywhere else on the system.  Then you can use `syncthing` on the filesystem you create on it, and all the files will be encrypted on disk.  It's a lot harder for an attacker to compromise the files, then.  (To compromise `syncthing-docker-encrypt`, all they have to do is pull out the hard drive, and get the encrypted directory password from the docker container environment variables which are stored in the clear in json.)

**Comment by PhracturedBlue** [comment]
I'm not very familiar with luks, but I thought that with luks, root could 'su' into the user's account and see all encrypted files.  I do not think syncthing-docker-encrypt is quite as bad as you make it out to be.  While anyone can easily extract the key sent to docker, that is only half of the requirement.  You must also extract the secret key from the docker image which should require dumping the docker filesystem image and locating and extracting the secret key.  Certainly possible, but not as easy as you make it out to be.

I really recommend using file-level encryption with syncthing (which I also do) but it is harder to deal with on Android.

resillio does this better
